### ISSUE TITLE
Separate Bounties from Open Positions and give it its own prominent place in the Doc Book.

### ISSUE THREAD

**Issue by sacshin** [Mi-Lan/dxDaoBlog#100]
Make it easy for readers to navigate to a list of existing DXdao bounties and to suggest new ones.
If possible, add a button for readers to share the bounty list on social media. /could also be useful for other sections of the Doc Book, e.g. open positions/

**Comment by KeenanLukeOM** [comment]
Good call!

Bounty separation is actually planned, but was kept together in the absence of bounties currently. I think it makes sense for this to exist on an upper level, so prospective contributors can easily find our active bounties.

Will keep the button in mind as well, and potentially open a dedicated Issue in the future.

**Comment by KeenanLukeOM** [comment]
Addressed by #105
