### ISSUE TITLE
/docs/Products/mesa/faq/ text implementation.

### ISSUE THREAD

**Issue by KeenanLukeOM** [Mi-Lan/dxDaoBlog#11]
Implement the following text to /docs/Products/mesa/faq/

https://pastebin.com/Zw5nsgQs

**Comment by Mi-Lan** [comment]
missing text @KeenanLukeOM

**Comment by KeenanLukeOM** [comment]
Hopefully this will resolve. https://pastebin.com/Zw5nsgQs

**Comment by KeenanLukeOM** [comment]
@Mi-Lan This issue was resolved with the first pull, closing!
