### ISSUE TITLE
Brand assets missing

### ISSUE THREAD

**Issue by mprasanjith** [Mi-Lan/dxDaoBlog#116]
It seems that the resources in the [brand assets](https://dxdocs.eth.link/docs/BrandingAssets/) page in DXdocs are missing.

![image](https://user-images.githubusercontent.com/25136207/150551782-6164be43-685e-4361-b5ba-fa6a8d8851dd.png)

![image](https://user-images.githubusercontent.com/25136207/150551904-26b410cd-e7be-4d8a-8a19-e50c3b09382d.png)

**Comment by KeenanLukeOM** [comment]
Thanks for this!

Definitely a problem, although I could swear it worked before? And since its pinned alongside the page I'm not sure why that would have changed.

Adding to my list here

**Comment by KeenanLukeOM** [comment]
What a silly mistake lol. The brand assets page has broken since links used to redirect directly to files within the old landing page.

Overhauling this page is on my docket.

**Comment by KeenanLukeOM** [comment]
Addressing/Addressed in #117
