### ISSUE TITLE
/docs/Governance/Alchemy/ text implementation

### ISSUE THREAD

**Issue by KeenanLukeOM** [Mi-Lan/dxDaoBlog#17]
Currently, this directory doesn't exist. Refer to issue #16. Once ratified, implement the following text to /docs/Governance/Alchemy/

https://pastebin.com/di6HRumd

**Comment by Mi-Lan** [comment]
missing link @KeenanLukeOM

**Comment by KeenanLukeOM** [comment]
The above link appears to work for me, I will create a separate paste in case there is some kind of issue with the previous. 

https://pastebin.com/k0tZUrcS
