### ISSUE TITLE
Configure categories with required information

### ISSUE THREAD

**Issue by KeenanLukeOM** [Mi-Lan/dxDaoBlog#2]
As far as formatting of categories, we are ready to move along with implementation. I do not expect these to be final, but rather close to it - and I would like to start formatting and including relevant information shortly.

Attached is a [link to show the desired categories](https://www.figma.com/file/GJHVXRV1s4VRhwgNOM8bNu/Book-Basic-Layout?node-id=0%3A1), and below I have included the raw text as well as notes regarding their implementation.

>**DXdao**

>Governance ️
>REP
>Daotalk
>Snapshot
>Alchemy

>Products 
>Swapr
>Roadmap
>Website http://swapr.eth.link/#/swap
>Omen
>Market Resolution Rules
>Roadmap
>Website https://omen.eth.link/#/liquidity
>Mesa
>Website https://mesa.eth.link/
>Rails
>Website https://rails.eth.link/
>Other

>DXD

>FAQ 

>Contributor Hub
>Our Philosophy
>Open Positions and Bounties
>Employment
>Worker Compensation
>Worker Proposals
>Performance and Career Development
>Vacation and Holidays
>Discrimination and Harassment
>Decentralized Communication Technologies 
>Standards of Conduct

> Meetings

> Branding Assets 

> Get Connected
>Website https://dxdao.eth.link/#/
>Twitter https://twitter.com/Dxdao_
>Discord https://discord.gg/4QXEJQkvHH
>Medium https://dxdao.medium.com/
>Etherscan https://etherscan.io/token/0xa1d65E8fB6e87b60FECCBc582F7f97804B725521
>Telegram https://t.me/dxDAO
>Forum https://daotalk.org/c/dx-dao/15

Quick notes,

1. "DXdao" is the largest category, but it doesn't make sense to expand/minimize this. Having it as a serperate "welcome" page will be the route we take. 

2. Blue text under "get connected" would act as links, these will be non-expandable and directly take you to the noted social. (The proper links are included in the above raw text)

3. "Website" under each respective product will likely end up similar to the get connected tab, where there are many external links with no internal information. I have input only website for the time being, and when we are near completion any additional links can be added.

4. Indents are internal categories (EG, Governance can be clicked on for its information, or expanded. REP Daotalk Snapshot and Alchemy would all be found after expanding the Governance tab.) 

If anything here is at all confusing just ask and I can explain in more detail or hop in a quick call.

**Comment by Mi-Lan** [comment]
![Screenshot 2021-01-14 at 23 16 22](https://user-images.githubusercontent.com/33226956/104655795-86c89780-56be-11eb-97d8-dd28bb233785.png)
@KeenanLukeOM Hey Keenan i implemented this changes and will push them shortly just one suggestion so we stay consistent the way this theme is supposed to be used i don't think that we need to make separate categories for every case.
![Screenshot 2021-01-14 at 23 19 01](https://user-images.githubusercontent.com/33226956/104656024-e9219800-56be-11eb-8c82-99727959eda2.png)
As you can see when you enter this category it gives you table of contents and you can access all the relevant parts. I thought i will just mention this so you keep it in mind while planning!

**Comment by KeenanLukeOM** [comment]
Thanks @Mi-Lan! I'll take a look at it as soon as you are ready. As I currently understand, there should be no issue with the categorization when in reference to https://pmarsceill.github.io/just-the-docs/docs/ui-components

Perhaps we could have a short call if there is any confusion! I'll keep that in mind for when we start the next steps. :)

**Comment by KeenanLukeOM** [comment]
Updates!

1.)
![image](https://user-images.githubusercontent.com/76129769/104963343-28860800-598f-11eb-8194-b1948476fce4.png)

As mentioned earlier today, ensure each product has its own dropdown. The reason I am bringing it up again, is that I made some minor updates to these categories on [the Figma draft.](https://www.figma.com/file/GJHVXRV1s4VRhwgNOM8bNu/Book-Basic-Layout?node-id=0%3A1)

2.)

Unsure exactly how Github works in this capacity, but "Meetings" and "Get Connected" are missing from the recent push. I believe since the issue is still considered open, that not everything has been addressed yet?

3.)

"Contributor Hub" appears to have its subcategories internally instead of on the sidebar. These should be consistent with the "Governance" and "Products" categories.



Beyond these three, I will open separate issues where applicable!

**Comment by KeenanLukeOM** [comment]
Ahhh, one more.

4.)
![image](https://user-images.githubusercontent.com/76129769/104964738-e14d4680-5991-11eb-9495-bf498386aa61.png)

Ensure consistent use of "DXdao", instead of "DxDao".
[reference](https://www.coingecko.com/en/coins/dxdao) 
[ref2](https://dxdao.eth.link/#/)
