### ISSUE TITLE
Integrate Calendar to /docs/Meetings/

### ISSUE THREAD

**Issue by KeenanLukeOM** [Mi-Lan/dxDaoBlog#33]
As discussed today, Airtable has a javascript embed feature. Holding this calendar here (and also individual entries in the case of the subcategories), will be optimal for user experience. Once a solution is found, I will open issues for the implementation of each subcategory. 

Here is the associated embed.

`<iframe class="airtable-embed" src="https://airtable.com/embed/shrsNufwx2gWfZ5LH?backgroundColor=teal&viewControls=on" frameborder="0" onmousewheel="" width="100%" height="533" style="background: transparent; border: 1px solid #ccc;"></iframe>`

**Comment by Mi-Lan** [comment]
I think we will have to use something like this since that is js implementation https://github.com/Airtable/airtable-ruby
