### ISSUE TITLE
Make social categories link directly to the relevant social, implement the following links

### ISSUE THREAD

**Issue by KeenanLukeOM** [Mi-Lan/dxDaoBlog#34]
I will be closing issues #9 and #12 as they will be addressed here.

Clicking on a Social link should send the user directly to said social. For example, "Twitter" under the Omen category should take a user directly to the Omen Twitter, as opposed to a separate page. This was discussed between myself and Violet, we need someone with a bit more knowledge of Ruby.

This is a quote from the previous issues. _"To reiterate, clicking these while in the category should take you directly to the sites, rather than open a page where you need to make an additional click."_

_____________

**Implement these socials to the specified location.**

**Omen**

/docs/Products/Omen/Twitter : https://twitter.com/Omen_eth

/docs/Products/Omen/Website : https://omen.eth.link/

**Swapr**

/docs/Products/Swapr/Twitter : https://twitter.com/SwaprEth

/docs/Products/Swapr/Website : https://swapr.eth.link/

**Mesa**

/docs/Products/Mesa/Twitter : https://twitter.com/mesa_eth

/docs/Products/Mesa/Website : https://mesa.eth.link/

**Rails**

/docs/Products/Rails/Twitter : https://twitter.com/Rails_eth

/docs/Products/Rails/Website : https://rails.eth.link/

**"Get Connected"**

/docs/GetConnected/discord/ : https://discord.gg/4QXEJQkvHH

/docs/GetConnected/etherscan/ : https://etherscan.io/token/0xa1d65E8fB6e87b60FECCBc582F7f97804B725521

/docs/GetConnected/forum/ : https://daotalk.org/c/dx-dao/15

/docs/GetConnected/medium/ : https://dxdao.medium.com/

/docs/GetConnected/telegram/ : https://t.me/dxDAO

/docs/GetConnected/twitter/ : https://twitter.com/Dxdao_

/docs/GetConnected/website/ : https://dxdao.eth.link/#/

**Comment by Mi-Lan** [comment]
![Screenshot 2021-02-25 at 18 53 53](https://user-images.githubusercontent.com/33226956/109195492-e07eb000-779a-11eb-812c-a62127ea1917.png)
As Keenan said the idea is to have these items below the getConnected be clickable links that take user to desired location...
