### ISSUE TITLE
Ensure necessary links lead internally rather than to a separate documentation page.

### ISSUE THREAD

**Issue by KeenanLukeOM** [Mi-Lan/dxDaoBlog#37]
When writing content, it has linked directly to other google docs. We are looking to address this by making these links direct to the relevant page on the documentation book itself.

I will mention each instance of this, and where it should point.

Current IPFS build : https://bafybeihekgnd4td64gc4st477akoyeov6sgvllvq6hfn7iwgy537n3ulra.ipfs.dweb.link/
______

From issue #36: /docs/Governance/Rep/, Paragraph 2. "Here is a link for How-to Submit a REP Boost Proposal on Alchemy."

- Make "How-to Submit a REP Boost Proposal on Alchemy." link directly to /docs/Governance/Rep/REP-Boost-Guide (Currently doesn't exist, from issue #35). Ensure that the text from Issue #36 is updated rather than the current IPFS build (although these are identical in this case).

From IPFS: /docs/ContributorHub/employment/, step 4 of Contributor onboarding. "Look at Open Positions and Bounties."

- Make "Open Positions and Bounties" link directly to /docs/ContributorHub/open-positions-and-bounties/

From IPFS: /docs/ContributorHub/employment/, step 9 of Contributor onboarding. "See the Worker Proposal Guide on how to submit your first proposal on Alchemy."

- Make "Worker Proposal Guide" link directly to /docs/ContributorHub/worker-proposals/Worker-Proposal-Guide (Currently doesn't exist, from issue #35)

From IPFS: /docs/ContributorHub/employment/, 2nd last sentence. "How-to: Submit You Worker Proposal on Alchemy Guide"

- Make "How-to: Submit You Worker Proposal on Alchemy Guide" link directly to /docs/ContributorHub/worker-proposals/Worker-Proposal-Guide (Currently doesn't exist, from issue #35)

From IPFS: /docs/ContributorHub/employment/, last sentence. "How-to: Alchemy DXD Vesting Proposal Guide"

- Make "How-to: Alchemy DXD Vesting Proposal Guide" link directly to /docs/ContributorHub/worker-proposals/DXD-Vesting-Guide (Currently doesn't exist, from issue #35)

From IPFS: /docs/ContributorHub/decentralized-communications-technologies/, Last sentence under "on-chain". "All governance decisions are made on DXdao’s voting platform, Alchemy, which is an on-chain voting system hosted on the Ethereum Mainnet."

- Make "Alchemy" link directly to /docs/Governance/Alchemy/

**Comment by Mi-Lan** [comment]
@KeenanLukeOM 
From IPFS: /docs/ContributorHub/employment/, 2nd last sentence. "How-to: Submit You Worker Proposal on Alchemy Guide"

Make "How-to: Submit You Worker Proposal on Alchemy Guide" link directly to /docs/ContributorHub/worker-proposals/Worker-Proposal-Guide (Currently doesn't exist, from issue #35)
From IPFS: /docs/ContributorHub/employment/, last sentence. "How-to: Alchemy DXD Vesting Proposal Guide"

Make "How-to: Alchemy DXD Vesting Proposal Guide" link directly to /docs/ContributorHub/worker-proposals/DXD-Vesting-Guide (Currently doesn't exist, from issue #35)

> Hey i didn't find these 2 ? Where should i link them?

**Comment by KeenanLukeOM** [comment]
I misinputted "employment", these can both be found at the bottom of /docs/ContributorHub/worker-proposals/

![image](https://user-images.githubusercontent.com/76129769/111552364-64470f00-873f-11eb-9fbb-6812a35c1c64.png)
