### ISSUE TITLE
Implement current hidden branding asset page from DXdao.eth.link to /docs/BrandingAssets

### ISSUE THREAD

**Issue by KeenanLukeOM** [Mi-Lan/dxDaoBlog#47]
Opening this in a separate issue, since it seemed to have needed some extra conversion. (Putting it into Ruby).

____

Take the [current hidden branding assets page](https://dxdao.eth.link/#/brand-assets), and implement it to /docs/BrandingAssets/

If there is an issue with this translation, make a comment and I will create a new branding asset page. 

After it has been implemented, I will be making text changes on my end.

**Comment by Mi-Lan** [comment]
@KeenanLukeOM Hey men i tried converting that html and css but there doesn't seem to be a good option as of now to do that...There is one long way of doing it but it isn't worth the effort
