### ISSUE TITLE
Introduce spacing to Categories

### ISSUE THREAD

**Issue by KeenanLukeOM** [Mi-Lan/dxDaoBlog#5]
Hopefully this makes sense as a separate issue, since the first was primarily content focused.

Replace the "DXdao" category with "Welcome". 

Add a unclickable group labelled "DXdao". Include everything below this except "Get connected".

Remove "Get Connected", and create a group with the same name.

Include all links at this higher level, making them visible without expanding a "Get connected" category.

.

Below I have included an example of Gitbook, where "Welcome" is ungrouped and above all others. "Primedao" is unclickable and is used to group together the relevant categories. "Links" is unclickable and is used to include those links at all times. 

[Here the site if that is easier.](https://docs.primedao.io/)

![image](https://user-images.githubusercontent.com/76129769/104966758-9255e000-5996-11eb-8c7e-7886e2fc4f06.png)

If formatting in such a way is not possible with Just the docs, ping me and I will work on a solution.

**Comment by Mi-Lan** [comment]
@KeenanLukeOM based on this issue https://github.com/Mi-Lan/dxDaoBlog/issues/2 and the issue above i see that you are trying to replicate git-book theme and kinda make it work on this one...i think that is not a good idea and that we should have chosen different theme in the first place....i will try to make it work but i'm not that much familiar with jekyll and will have to dig in to find out...

**Comment by KeenanLukeOM** [comment]
As mentioned, if this isn't a possibility in Just the docs its no issue - I just felt that it would be beneficial to have. 

If not possible or too much work, please ignore and close this issue.
