### ISSUE TITLE
Replace and gendered language with its non-gendered counterpart.

### ISSUE THREAD

**Issue by KeenanLukeOM** [Mi-Lan/dxDaoBlog#80]
Soft consensus was reached that documentation in this setting should remain as gender neutral as feasible. This issue is indicative of replacing any use of "he", "she", or any other gendered language with non-gendered language such as "they", "their", etc..

**Comment by Mi-Lan** [comment]
@KeenanLukeOM Currently gender politics is very touchy subject in my opinion and we should avoid getting down that rabbit hole since its close to politics and can create issues down the line. I would suggest just rephrasing text not to include genders.

**Comment by KeenanLukeOM** [comment]
@Mi-Lan This has been addressed in #83 actually! That's my thoughts as well. Everything gendered such as he/she was changed to they/their.
