### ISSUE TITLE
Add a button/link to this repo within the Doc Book, so readers can easily suggest features or report issues.

### ISSUE THREAD

**Issue by sacshin** [Mi-Lan/dxDaoBlog#99]
Give https://github.com/Mi-Lan/dxDaoBlog/issues a place within the Doc Book.

**Comment by KeenanLukeOM** [comment]
Hey!

DXdocs actually has this on the upper right hand corner:

![image](https://user-images.githubusercontent.com/76129769/125827271-60b72b09-a422-4925-b047-eb5ab774a048.png)

Are you referring specifically to opening an issue/sending directly to the issue landing?

**Comment by sacshin** [comment]
The link text saying "DXdao blog" can be confusing, and I've even missed it for that reason.
Since it already exists, no change is needed really apart from probably renaming it to "submit a feature/issue"?

**Comment by KeenanLukeOM** [comment]
Addressing in #117
